USE fuel;
-- 1. What is the average price of Gasoil Grade 2 across all provinces?
SELECT 
avg(Price_Arg_Pesos) 
as Average_Price 
from fuel_1
where Product_Type = "Gasoil Grade 2";
-- 2. Which company has the highest total sales by city?
Select Company_Name, City, sum(Price_Arg_PESOS) as Total_Sales
from fuel_1
group by Company_Name, City
order by Total_Sales DESC
Limit 1;
-- 4. Which region has the highest average price for Compressed Natural Gas?
select Region, avg(Price_Arg_Pesos) as Highest_Ave_Price
from fuel_1
Where Product_Type = "Compressed Natural Gas"
group by Region
order by Highest_Ave_Price desc
limit 1;
-- Can we observe any significant difference in fuel prices between daytime and nighttime shifts?
select Shift_Type, sum(Price_Arg_Pesos) as Total_Sales
from fuel_1
group by Shift_Type
order by Total_Sales DESC;
-- 7. How many different types of products are sold by the company "AUTOMOVIL CLUB ARGENTINO"?
SELECT count(distinct Product_Type) AS Product_Count
FROM fuel_1
WHERE Company_Name = 'AUTOMOVIL CLUB ARGENTINO';
-- 8. Which city in the Patagonia region has the highest recorded price for any fuel type?
SELECT City, sum(Price_Arg_Pesos) AS Price
FROM fuel_1
WHERE Region = 'Patagonia'
GROUP BY City
ORDER BY Price DESC
LIMIT 1;
-- 9. What are the top 10 companies by sales revenue in 2023? 
SELECT Company_Name, SUM(Price_Arg_Pesos) AS Revenue
FROM fuel_1
GROUP BY Company_Name
ORDER BY Revenue DESC
LIMIT 10;
-- 10. What is the total revenue generated by each flagged company if we assume each price corresponds to one sale?
SELECT Flag_Company, SUM(Price_Arg_Pesos) as Revenue
FROM fuel_1
GROUP BY Flag_Company
ORDER BY Revenue DESC;
-- 12. What was the highest and lowest prices of Gasoil Grade 2 in the province of Buenos Aires during the year 2023?
SELECT Product_Type,Province, Year, Price_Arg_Pesos as Highest_Price
FROM fuel_1
WHERE Product_Type = 'Gasoil Grade 2' AND Province = 'Buenos Aires' AND Year = 2023
ORDER BY Highest_Price DESC
LIMIT 1;
-- What was the highest and lowest prices of Gasoil Grade 2 in the province of Buenos Aires during the year 2023?
SELECT Product_Type,Province,Year,Price_Arg_Pesos as Lowest_Price
FROM fuel_1
WHERE Product_Type = 'Gasoil Grade 2' AND Province = 'Buenos Aires' AND Year = 2023
ORDER BY Lowest_Price
LIMIT 1;
-- 15. What was the product that showed the highest sales?
SELECT Product_Type AS Product,
SUM(Price_Arg_Pesos) AS Highest_Price
FROM fuel_1
GROUP BY Product
ORDER BY Highest_Price DESC
LIMIT 1;
-- 16. Was there any month in the year 2023 where a trend of increasing prices for all products sold by a specific company was observed?
SELECT Montgh, 
SUM(Price_Arg_Pesos) AS Price
FROM fuel_1
WHERE Year = 2023
GROUP BY Montgh
ORDER BY Montgh;
-- 17. Which company showed the greatest volatility in the prices of all its products during the year 2023?
SELECT Company_Name,
stddev(Price_Arg_Pesos) AS Price_Stddev
FROM fuel_1
WHERE Year = 2023
GROUP BY Company_Name
ORDER BY Price_Stddev DESC
LIMIT 1;


